# how to show docstring.....
def sum(a,b):
    """ this program for addition of two numbers we can optain the docstring in the program....."""# we can show the docstring in the program...
    c=a+b
    print(c)
    print(sum.__doc__)# this is the method for showing docstring in the program...

sum(1,1);